services:
  api:
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - jumpnetwork
    depends_on:
      - db

  db:
    image: jump-database
    ports:
      - "5432:5432"
    networks:
      - jumpnetwork

networks:
  jumpnetwork:
    driver: bridge
