// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -package invoice -destination=mock.go
//

// Package invoice is a generated GoMock package.
package invoice

import (
	context "context"
	reflect "reflect"

	models "github.com/HLerman/test/internal/business/models"
	gomock "go.uber.org/mock/gomock"
)

// MockDb is a mock of Db interface.
type MockDb struct {
	ctrl     *gomock.Controller
	recorder *MockDbMockRecorder
}

// MockDbMockRecorder is the mock recorder for MockDb.
type MockDbMockRecorder struct {
	mock *MockDb
}

// NewMockDb creates a new mock instance.
func NewMockDb(ctrl *gomock.Controller) *MockDb {
	mock := &MockDb{ctrl: ctrl}
	mock.recorder = &MockDbMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDb) EXPECT() *MockDbMockRecorder {
	return m.recorder
}

// AddInvoice mocks base method.
func (m *MockDb) AddInvoice(ctx context.Context, invoice models.Invoice) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddInvoice", ctx, invoice)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddInvoice indicates an expected call of AddInvoice.
func (mr *MockDbMockRecorder) AddInvoice(ctx, invoice any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddInvoice", reflect.TypeOf((*MockDb)(nil).AddInvoice), ctx, invoice)
}
